// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoYK3iAmBE3cRxcZEAO9UpZfK7KGrk5Gc',
    appId: '1:175147512443:web:fb55b6ab7b902d4cdd28de',
    messagingSenderId: '175147512443',
    projectId: 'revember-fd629',
    authDomain: 'revember-fd629.firebaseapp.com',
    storageBucket: 'revember-fd629.appspot.com',
    measurementId: 'G-W1PXC42YDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb7-3lPAhAg38n9qM-AgR0L7b1ny-dBAI',
    appId: '1:175147512443:android:0178db1f25bb3d0bdd28de',
    messagingSenderId: '175147512443',
    projectId: 'revember-fd629',
    storageBucket: 'revember-fd629.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaS6KN_sEWPykvUkiY6hCqy6teBEnQzu0',
    appId: '1:175147512443:ios:53b10541e108721edd28de',
    messagingSenderId: '175147512443',
    projectId: 'revember-fd629',
    storageBucket: 'revember-fd629.appspot.com',
    iosClientId: '175147512443-a9rad95so7vk7sft2nhgud5dcu0dl8hn.apps.googleusercontent.com',
    iosBundleId: 'com.example.revemberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaS6KN_sEWPykvUkiY6hCqy6teBEnQzu0',
    appId: '1:175147512443:ios:53b10541e108721edd28de',
    messagingSenderId: '175147512443',
    projectId: 'revember-fd629',
    storageBucket: 'revember-fd629.appspot.com',
    iosClientId: '175147512443-a9rad95so7vk7sft2nhgud5dcu0dl8hn.apps.googleusercontent.com',
    iosBundleId: 'com.example.revemberApp',
  );
}
